apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
#  - provider.yaml
#  - aws-secret.yaml
#  - provider-config.yaml
#  - db.yaml
