apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase1
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase2
resources:
  - provider.yaml
  - aws-secret.yaml
spec:
  demandOn:
    - name: crossplane-infra-phase1

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase3
resources:
  - provider-config.yaml
spec:
  demandOn:
    - name: crossplane-infra-phase2

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase4
resources:
  - db.yaml
spec:
  demandOn:
    - name: crossplane-infra-phase4

---
