apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-infra-phase1
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ../phase2/provider.yaml
  - ../phase2/aws-secret.yaml
